apiVersion: v1
kind: Secret
metadata:
    name: url-shortener-db
    namespace: url-shortener
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:DTG6bZZr4E5IRonlUmudymdkcrl3fXn2x9zHZW0vPsOHfZXBNrxz+LFTa2y/jfuJ,iv:1PiIozj4rScJDO+k8/82g4jgD5YVkdzlgWeePxp0jUc=,tag:SQ336fNn9tp7kVZEVEMt7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMGxwYXFYVHFQUkVCVkUx
            NmlrekQvMXFXNE1xYW83QkFrL3ZIc3YwWWlNCk5zVTR1QmlUSE1uNEdJay9aR3BM
            ZmlNWHg0dU41NExKWDNZSitBdkZqaTQKLS0tIFp2bjlXRVYzYTh0bG9KQ25ZbERF
            UVdVWHBMODYweFBYRDAvWHpVb0hEVjAKxunUoDpKXKb68ySJgXOKos3f/V29bMMS
            pFQxNb9qHQYoN/UkUnKtY+dd+om3DIGnFzAZGeWDBSe5WktjnduKWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age143zk4xcwfzwsyahkuwx5ednndsqhx88tfgkh5xs9mlpgjq04tscssa42t8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T18:27:55Z"
    mac: ENC[AES256_GCM,data:/t1tfpFt1oRUXfiZRwK4DF1InK5sTPBX3WkBR6BZAWaNE2tlZ6aGsmTHSiOcx1G4G1KFUWwIBtj/yWLWIciL53JKk4aBiz0VSwEAOJBRZFgAK8O6ko+iGYRnaU6ztpifdlFGYSJTJD7+uwOeXHE66Q4Dx8G5mEO+dhLa9H03WuE=,iv:XROSnzmXGm8/9H1SeOQeFNHHzRvibnWfu8nFPzClveQ=,tag:+YE2peE/JIWYVCxzySLxDw==,type:str]
    version: 3.13.3
