apiVersion: v1
kind: Namespace
metadata:
  name: url-shortener
  labels:
    # Enforce the Kubernetes "restricted" Pod Security Standard.
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
