{{- if .Values.dbSecret.create.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dbSecret.name }}
  labels: {{- include "shortener.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ required "dbSecret.create.password is required" .Values.dbSecret.create.password | quote }}
{{- end }}
